### ISSUE TITLE
Standalone tarbar release

### ISSUE THREAD

**Issue by tszming** [treasure-data/td-agent#38]
It would be useful if we can build td-agent as a tarbar so we can extract it to any path and run immediately without messing with the OS package manager like apt or yum. (we use supervisord to mange it instead)

**Comment by fenggolang** [comment]
I also want a td-agent tarbal, because we can not get to root privileges to yum install td-agent

**Comment by repeatedly** [comment]
tarball is useless because you need to setup script / other directories by manual.
I mentioned it previous comment.

If you don't have a privilege of root, using ruby-build and fluentd gems seem enough.
