### ISSUE TITLE
Start td-agent failed with error 'unexpected error error="default value specified twice for tag"'

### ISSUE THREAD

**Issue by lansz** [treasure-data/td-agent#63]
After upgrade td-agent to td-agent-1.1.20-0.x86_64, td-agent service start failed with error 'unexpected error error="default value specified twice for tag"', event after I empty td-agent.conf, the error still exists.

Downgrade td-agent to td-agent-1.1.18-0.x86 and everything back to normal.

OS: CentOS release 6.3 (Final)

**Comment by repeatedly** [comment]
No response.

**Comment by sumit-gupta-sgt** [comment]
I am also facing same issue after upgrading from v1 to v2 ...Any update on this?

Thanks.
Sumit
