### ISSUE TITLE
MongoDB driver v1.8.6 raise "Exceded maximum insert size of xxx" error 

### ISSUE THREAD

**Issue by fetaro** [treasure-data/td-agent#71]
When fluentd try to insert a large chunk into MongoDB, raise error "Exceded maximum insert size of xxx", because MongoDB has limit that query size must be less than 16MBytes and Ruby-MongoDB-driver v1.8.6 also has another limitation about documents size too.
But Ruby-MongoDB-driver v1.9.0 can handle large amount of documents by using self splitting.
(see https://jira.mongodb.org/browse/RUBY-533)
 
I recommend you to change  Ruby-MongoDB-driver version from v1.8.6 into v1.9.0- .

**Comment by repeatedly** [comment]
This is td-agent repository, not fluent-plugin-mongo.
Please post this issue on fluent-plugin-mongo.
