### ISSUE TITLE
error during stop in init script

### ISSUE THREAD

**Issue by uwebartels** [treasure-data/td-agent#73]
Hiho,

when trying to run "service stop td-agent" on redhat I get an error if td-agent is not running.
as I don't see this as an error, I'd like to ask for a fix.
We are having problems with automation with chef, when the script throws an error.

if you add the line 
[ $RETVAL -eq 7 ] && return 0
before the last line 
return $RETVAL
in the stop function everything is fine.

Best...
Uwe

**Comment by repeatedly** [comment]
Sorry for the delay.

Is this still happen with latest td-agent 2?

**Comment by uwebartels** [comment]
No. This problem occurs only on td-agent1. We are already about roll out td-agent2.

Best...
Uwe

**Comment by repeatedly** [comment]
Ah, I see.
td-agent 1 is now maintenance mode and now almost users moved to td-agent 2.
Close this issue.

If td-agent 1 user who can't upgrade to td-agent 2 hit this issue, please reopen.
