### ISSUE TITLE
Support for RedHat v. 7

### ISSUE THREAD

**Issue by potter-s** [treasure-data/td-agent#74]
The installation (I'm using Opscode Chef) fails on RHEL7. Not all that surprising as this page - http://docs.treasuredata.com/articles/td-agent - suggests only 6 is supported. The problem is the lack of a version 7 init script.

Do you anticipate supporting this version and, if so, do you know the likely time frame?

**Comment by repeatedly** [comment]
Please use td-agent 2.
td-agent 1 is old stable and no v7 support plan.

http://docs.fluentd.org/articles/td-agent-v1-vs-v2
