### ISSUE TITLE
Debian init script errors

### ISSUE THREAD

**Issue by bkersten** [treasure-data/td-agent#76]
Hello,

I'm attempting to use fluentd on Ubuntu and ran up against a few issues. I've discovered two bugs in your init script for debian systems.

1) The status command is missing a pidfile argument and will always report running

https://github.com/treasure-data/td-agent/blob/master/debian/td-agent.init#L154

	status_of_proc "$DAEMON" ruby && exit 0 || exit $?

Should instead be

	status_of_proc -p $PIDFILE "$DAEMON" ruby && exit 0 || exit $?

2) The user argument is being passed as -c (configuration file)

https://github.com/treasure-data/td-agent/blob/master/debian/td-agent.init#L53

	START_STOP_DAEMON_ARGS="${START_STOP_DAEMON_ARGS} -c ${USER}"

Should instead be

	START_STOP_DAEMON_ARGS="${START_STOP_DAEMON_ARGS} --user ${USER}"

**Comment by repeatedly** [comment]
Sorry for the delay reply.

td-agent 1 is now maintenance mode.
Could you reopen this issue on new repository? 

https://github.com/treasure-data/omnibus-td-agent
