### ISSUE TITLE
unable to build debian package

### ISSUE THREAD

**Issue by chansen736** [treasure-data/td-agent#78]
I'm attempting to build the debian package on a stripped-down debian, and it produces a lot of errors and fails to create the package. I started fixing it by installing additional dependencies and even some hacky stuff; see go.sh, what i was using to build. The commented out bits were used to try to fix my way through it. I keep running into new issues, so thought I'd ask here if I'm missing something obvious.

Output file and build script available here: https://gist.github.com/chansen736/930acdb54267e074f468

root@e0437c5902b3:/# uname -a
Linux e0437c5902b3 3.16.0-0.bpo.4-amd64 #1 SMP Debian 3.16.7-ckt4-3~bpo70+1 (2015-02-12) x86_64 GNU/Linux

**Comment by repeatedly** [comment]
Sorry I missed this PR because we have already moved to omnibus-td-agent: https://github.com/treasure-data/td-agent#note

Try omnibus-td-agent instead of this repository.
