### ISSUE TITLE
[td-agent] - latest version fluentd ?

### ISSUE THREAD

**Issue by JulienChampseix** [treasure-data/td-agent#86]
Hi team,

is it planned to have td-agent version integrating the latest version of fluentd (0.12.17) ? As mentionned there http://www.fluentd.org/blog/fluentd-v0.12.17-has-been-released

Thanks,
Julien.

**Comment by repeatedly** [comment]
Sorry, we have already moved to omnibus-td-agent: https://github.com/treasure-data/td-agent#note

BTW, td-agent 2.3.1 includes fluentd v0.12.20.
