### ISSUE TITLE
Upstart/systemd units?

### ISSUE THREAD

**Issue by frioux** [treasure-data/td-agent#87]
Would you all be willing to accept patches to create an upstart and systemd unit file for td-agent instead of always using the old sysv shell script setup?  I'm happy to give it a shot, but would like to make sure that it's welcome first.

Thanks.

**Comment by jantman** [comment]
There's a pull request open - #82 - for a systemd unit file, but it seems to have been opened in July and unmerged. Admittedly, the PR just adds the unit to the source tree, it doesn't actually include it in the RPM.

**Comment by repeatedly** [comment]
Sorry, we have already moved to omnibus-td-agent: https://github.com/treasure-data/td-agent#note
So we will discuss upstart/systemd support on omnibus-td-agent repository instead.
